# Generated by Django 5.0.6 on 2024-07-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_room_options_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', 'created']},
        ),
    ]
