# Generated by Django 5.0.6 on 2024-07-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('publication_date', models.DateTimeField()),
                ('url', models.URLField()),
                ('url_to_image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
